// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetPal.Data;

#nullable disable

namespace PetPal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403190131_AddPetEventsModels")]
    partial class AddPetEventsModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetPal.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PetId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDateTime = new DateTime(2025, 4, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            AppointmentType = "Vet",
                            Location = "Happy Paws Clinic",
                            Notes = "Regualar check-up and vaccination update",
                            PetId = 1,
                            PetName = "Joey"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDateTime = new DateTime(2025, 4, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            AppointmentType = "Grooming",
                            Location = "Pet Smart",
                            Notes = "Full grooming with nail trim",
                            PetId = 2,
                            PetName = "Mavis"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDateTime = new DateTime(2025, 4, 12, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            AppointmentType = "Vet",
                            Location = "Dog & Cat Hospital - East Hill",
                            Notes = "Follow-up for paw stitches",
                            PetId = 3,
                            PetName = "Ollie"
                        });
                });

            modelBuilder.Entity("PetPal.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("PetBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("PetBreed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetGender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Pet");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            ImageUrl = "/images/Joey.jpg",
                            PetAge = 15,
                            PetBirthday = new DateTime(2010, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetBreed = "Japanese Bobtail",
                            PetGender = "Male",
                            PetName = "Joey",
                            PetType = "Cat",
                            UserId = 1
                        },
                        new
                        {
                            PetId = 2,
                            ImageUrl = "/images/Mavis.jpg",
                            PetAge = 4,
                            PetBirthday = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetBreed = "Australian Shepard",
                            PetGender = "Female",
                            PetName = "Mavis",
                            PetType = "Dog",
                            UserId = 2
                        },
                        new
                        {
                            PetId = 3,
                            ImageUrl = "/images/Ollie.jpg",
                            PetAge = 4,
                            PetBirthday = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetBreed = "Golden Doodle",
                            PetGender = "Male",
                            PetName = "Ollie",
                            PetType = "Dog",
                            UserId = 2
                        },
                        new
                        {
                            PetId = 4,
                            ImageUrl = "",
                            PetAge = 4,
                            PetBirthday = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetBreed = "Labrador",
                            PetGender = "Male",
                            PetName = "Max",
                            PetType = "Dog",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PetPal.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medication")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReminderNote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ScheduleTime")
                        .HasColumnType("time");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("PetId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            PetId = 1,
                            PetName = "Joey",
                            Portion = "1/4 cup dry food",
                            Recurrence = "Daily",
                            ReminderNote = "Morning feeding",
                            ScheduleDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduleTime = new TimeSpan(0, 8, 0, 0, 0),
                            ScheduleType = "Feeding"
                        },
                        new
                        {
                            ScheduleId = 2,
                            PetId = 2,
                            PetName = "Mavis",
                            Portion = "1/2 cup of OpenFarm food",
                            Recurrence = "Daily",
                            ReminderNote = "Morning feeding",
                            ScheduleDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduleTime = new TimeSpan(0, 11, 0, 0, 0),
                            ScheduleType = "Feeding"
                        },
                        new
                        {
                            ScheduleId = 3,
                            Dosage = "5 ml",
                            Medication = "Antibiotic",
                            PetId = 3,
                            PetName = "Ollie",
                            Recurrence = "Daily",
                            ReminderNote = "After evening meal",
                            ScheduleDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduleTime = new TimeSpan(0, 18, 0, 0, 0),
                            ScheduleType = "Medication"
                        });
                });

            modelBuilder.Entity("PetPal.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TrainingNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainingId");

                    b.HasIndex("PetId");

                    b.ToTable("Training");

                    b.HasData(
                        new
                        {
                            TrainingId = 1,
                            PetId = 1,
                            PetName = "Joey",
                            TrainingDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingDurationMinutes = 20,
                            TrainingNotes = "Interactive toy session indoors.",
                            TrainingType = "Play Time"
                        },
                        new
                        {
                            TrainingId = 2,
                            PetId = 2,
                            PetName = "Mavis",
                            TrainingDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingDurationMinutes = 30,
                            TrainingNotes = "Walked around the park. Very energetic.",
                            TrainingType = "Walking"
                        },
                        new
                        {
                            TrainingId = 3,
                            PetId = 3,
                            PetName = "Ollie",
                            TrainingDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainingDurationMinutes = 60,
                            TrainingNotes = "Practiced recall and fetch. Good progress.",
                            TrainingType = "New Trick"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "$2a$11$wp5ru8F9xrKXCbHAz1eDf.CJYczC6Z8WFaKtaSNG99Kla9u6Peqim",
                            UserName = "Josie"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "$2a$11$W11KvxC86p7FMW452vF/7ePDQ7GsJKp1uFnn.ywxghsl6CItcSwzG",
                            UserName = "Walter"
                        });
                });

            modelBuilder.Entity("PetPal.Models.Appointment", b =>
                {
                    b.HasOne("PetPal.Models.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPal.Models.Pet", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetPal.Models.Schedule", b =>
                {
                    b.HasOne("PetPal.Models.Pet", "Pet")
                        .WithMany("Schedules")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPal.Models.Training", b =>
                {
                    b.HasOne("PetPal.Models.Pet", "Pet")
                        .WithMany("Training")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetPal.Models.Pet", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
